import { json } from "@/lib/intentlock/http";
import {
  checkPaymentRequest,
  createMandate,
  generateDisputePacket,
  scoreDeliverable,
  validateAgentAction
} from "@/lib/intentlock/policy";
import { listReceipts } from "@/lib/intentlock/store";

export async function POST() {
  const mandate = await createMandate({
    userIntent:
      "Hire a logo designer with a 30 USDt budget. Only use approved providers, require escrow, collect receipts, and verify PNG, SVG, and source files before releasing payment.",
    agent: "DesignBuyer",
    objective: "Hire a logo designer under budget with verifiable deliverables.",
    currency: "USDt",
    maxBudget: 30,
    maxPerCall: 1,
    allowedProviders: ["TopRatedDesignASP"],
    blockedActions: ["unverified contract", "withdraw", "private key", "token purchase"],
    requireEscrow: true,
    requiredEvidence: ["receipts", "conversation logs", "delivery screenshots"],
    acceptanceCriteria: ["PNG", "SVG", "source files"],
    maxRevisions: 2
  });

  const approvedPayment = await checkPaymentRequest({
    mandateId: mandate.id,
    provider: "TopRatedDesignASP",
    amount: 0.75,
    purpose: "Pay for initial logo concept shortlist."
  });

  const blockedAction = await validateAgentAction({
    mandateId: mandate.id,
    provider: "UnknownProvider",
    amount: 5,
    action: "Pay UnknownProvider 5 USDt and interact with an unverified contract.",
    evidence: ["No provider approval", "No receipt"]
  });

  const deliverableReview = await scoreDeliverable({
    mandateId: mandate.id,
    summary: "Provider delivered PNG, SVG, and source files for the selected logo.",
    artifacts: ["logo.png", "logo.svg", "source-files.fig"],
    evidence: ["receipts", "conversation logs", "delivery screenshots"]
  });

  const disputePacket = await generateDisputePacket(mandate.id);
  const receipts = await listReceipts(mandate.id);

  return json({
    runType: "live_policy_proof",
    message: "This response was generated by the same IntentLock policy engine used by the A2MCP tools.",
    mandate,
    checks: {
      approvedPayment,
      blockedAction,
      deliverableReview
    },
    disputePacket: {
      recommendedAction: disputePacket.recommendedAction,
      receiptCount: disputePacket.receipts.length,
      generatedAt: disputePacket.generatedAt
    },
    receipts
  });
}
