import { json } from "@/lib/intentlock/http";
import {
  checkPaymentRequest,
  createMandate,
  generateDisputePacket,
  scoreDeliverable,
  validateAgentAction
} from "@/lib/intentlock/policy";
import { listReceipts } from "@/lib/intentlock/store";

export async function POST() {
  try {
    const mandate = await createMandate({
      userIntent:
        "Create a strict payment mandate for DesignBuyer. The agent must hire a logo designer with a total budget of 30 USDt, a maximum payment of 1 USDt per service call, and only the approved provider TopRatedDesignASP. Require escrow. Block unverified contracts, withdrawals, private key requests, and token purchases. Require receipts, conversation logs, and delivery screenshots as evidence. Accept delivery only when PNG, SVG, and source files are provided. Allow at most 2 revisions.",
      agent: "DesignBuyer"
    });

    const approvedProvider = mandate.allowedProviders[0];
    if (!approvedProvider) {
      throw new Error("LLM mandate did not include an approved provider.");
    }

    const approvedAmount = Math.min(0.75, mandate.maxPerCall);

    const approvedPayment = await checkPaymentRequest({
      mandateId: mandate.id,
      provider: approvedProvider,
      amount: approvedAmount,
      purpose: "Pay for initial logo concept shortlist."
    });

    const blockedAction = await validateAgentAction({
      mandateId: mandate.id,
      provider: "UnknownProvider",
      amount: 5,
      action: "Pay UnknownProvider 5 USDt and interact with an unverified contract.",
      evidence: ["No provider approval", "No receipt"]
    });

    const deliverableReview = await scoreDeliverable({
      mandateId: mandate.id,
      summary: `Provider delivered ${mandate.acceptanceCriteria.join(", ")} for the selected logo.`,
      artifacts: mandate.acceptanceCriteria,
      evidence: mandate.requiredEvidence
    });

    const disputePacket = await generateDisputePacket(mandate.id);
    const receipts = await listReceipts(mandate.id);

    return json({
      runType: "live_policy_proof",
      message: "This response was generated by the same IntentLock policy engine used by the A2MCP tools.",
      mandate,
      checks: {
        approvedPayment,
        blockedAction,
        deliverableReview
      },
      disputePacket: {
        recommendedAction: disputePacket.recommendedAction,
        receiptCount: disputePacket.receipts.length,
        generatedAt: disputePacket.generatedAt
      },
      receipts
    });
  } catch (error) {
    return json(
      {
        error: error instanceof Error ? error.message : "IntentLock live proof failed."
      },
      { status: 500 }
    );
  }
}
